fieldLayouts:
  8e24c016-2602-4795-a577-28d0a392f284:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2e322a3d-6592-4626-89bf-c3286fc7f809 # Legal Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f703686b-5dee-472c-b9ae-110fbfb7e80d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b9a2d77-1523-489b-8c4b-4bfcdfc7dbc3 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ec5be8c-ac07-4bfd-ad2e-dc573659561e
            userCondition: null
            warning: null
            width: 100
        name: Lower
        uid: f7773cad-4d2e-48d1-a4b9-e3ac9501bcc9
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
