field: ea94f442-5271-4806-9615-d5646aa78587
fieldLayouts:
  07002c64-ca94-4aa8-a5f8-5363200ed60f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 78edba3e-0c3b-4229-a26a-38a8b83a1c35 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f5329fb-9562-4edd-aa71-0beac0a366b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fb8838-f4d8-4a38-9156-1122b6ee8786 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdcc962d-49fb-4dea-9f5e-1f897f4f4c22
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 082c5614-1d5d-4619-bde0-482749dbd536 # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09647b42-268c-4a38-883b-03511419c13f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb5131b2-4ff6-4d4f-ab2b-eae30bf5565f
        userCondition: null
fields:
  17fb8838-f4d8-4a38-9156-1122b6ee8786: # Body
    columnSuffix: rxbfvjrl
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  78edba3e-0c3b-4229-a26a-38a8b83a1c35: # Heading
    columnSuffix: yfaxgvjt
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  082c5614-1d5d-4619-bde0-482749dbd536: # Accordion
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordion
    instructions: null
    name: Accordion
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 283683598
      columns:
        __assoc__:
          -
            - 34d757c2-6a46-4fac-abca-c39b46a73934 # Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 883ce90a-ab3e-4732-a747-7441c90a4b61 # Body
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_accordion}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: accordion
name: Accordion
sortOrder: 1
