field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  b5167025-6217-469b-85b3-acabc536f2e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a933287e-e898-4dfe-b29f-7cda0599afd2 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 802b89d1-bb68-4726-be09-328a9180b515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 978805eb-fd33-418c-bc35-8c5f9919b7ff # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25df3703-8503-4eb0-b04c-82401e518ec5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad03bfbb-c009-4645-9510-8473385a2dfa
        userCondition: null
fields:
  978805eb-fd33-418c-bc35-8c5f9919b7ff: # Description
    columnSuffix: ytpfogdk
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  a933287e-e898-4dfe-b29f-7cda0599afd2: # Heading
    columnSuffix: tgpsareg
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contactForm
name: 'Contact Form'
sortOrder: 10
