field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  5e3dd6ba-183b-46be-afbf-b95ec744dd86:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: db3fcb60-f719-40d3-bad4-77dd112dee6b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 255ab9e4-a3f0-471c-9207-fe3854453443
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77efd199-d2df-4fbf-8a4b-a55cb0261ad7 # Address Details
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 546d3190-b0e6-4e36-9df8-3aad1c061cad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d3e1a74-a0ab-47fe-8031-c8e9c8765735
        userCondition: null
fields:
  77efd199-d2df-4fbf-8a4b-a55cb0261ad7: # Address Details
    columnSuffix: muqyvaga
    contentColumnType: text
    fieldGroup: null
    handle: addressDetails
    instructions: "Accepts either longitude and latitude\r\nFor longitude an latitude separated by comma : 22.248555732573216,114.16714855492346\r\nFor address example : digital butter hong kong"
    name: 'Address Details'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: 'digital butter hong kong'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  db3fcb60-f719-40d3-bad4-77dd112dee6b: # Heading
    columnSuffix: zpmddbdm
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: googleMapEmbed
name: 'Google Map Embed'
sortOrder: 5
