field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  15a9103b-5a94-4088-9261-598fe7615b5a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 614e8403-7e46-4e90-bfee-32b96e22392d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2f4aced-b83a-4c6e-9fa1-209b64bb4ae8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 171101f6-dccd-4801-bec2-8f4dec8fe074 # Address Details
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76858812-b9c0-4d39-8242-b1122de5908e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 838d9092-d94f-404b-9967-93a2a11f85ad
        userCondition: null
fields:
  614e8403-7e46-4e90-bfee-32b96e22392d: # Heading
    columnSuffix: yzuodjby
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  171101f6-dccd-4801-bec2-8f4dec8fe074: # Address Details
    columnSuffix: qdpwzcam
    contentColumnType: text
    fieldGroup: null
    handle: addressDetails
    instructions: "Accepts Address or Lat + Long\r\n"
    name: 'Address Details'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: googleMapEmbed
name: 'Google Map Embed'
sortOrder: 9
