field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  8152a7ca-438b-4cd9-9b8e-623dbe39f9d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 79aa842e-51cb-4aa2-887c-d237fc2a404f # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0cbda81-98a8-419c-9155-bf59833ceadd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e4337db-0083-4a95-8f08-bbadd4955177 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 006fe0c4-9b9f-443b-97b3-3ad8fb3f5c39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c6f7825-37ef-467e-9bd9-880b6ebb7237 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ac596cf-c4f2-4864-b50c-ec1c72544183
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c074f4fe-289c-415e-9e81-8ce32db9b862 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66587069-7eaf-4cfc-a6c3-07954498c29b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7cc8251c-5285-4f9a-b7d0-60ce4e7e4a61
        userCondition: null
fields:
  1c6f7825-37ef-467e-9bd9-880b6ebb7237: # Description
    columnSuffix: aluimwfb
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  2e4337db-0083-4a95-8f08-bbadd4955177: # Subtitle
    columnSuffix: jotrgmgx
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  79aa842e-51cb-4aa2-887c-d237fc2a404f: # Heading
    columnSuffix: pgvghwdi
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c074f4fe-289c-415e-9e81-8ce32db9b862: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: heroBanner
name: 'Hero Banner'
sortOrder: 3
