field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  22af9d9e-d7ec-4824-a70f-638b0937b28c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c8d24909-9834-4afa-9c6d-dfc0f16ef9d2 # Slide
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33267447-d667-4e65-b3dc-a34da44e094c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48ee3a09-b908-4cd0-965d-ae054114aea3
        userCondition: null
fields:
  c8d24909-9834-4afa-9c6d-dfc0f16ef9d2: # Slide
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slide
    instructions: null
    name: Slide
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1471601294
      columns:
        __assoc__:
          -
            - 35157187-1d59-475f-a134-67fb797046b6
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c815fb61-b24b-4de7-a1d1-d8bbd8b583f4
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fa2e73aa-a1f5-480d-b37f-9961f67a64a1
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 32083c7e-92b0-401c-8469-c39692c0e47b
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_6_slide}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: slider
name: Slider
sortOrder: 4
