field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  099dac7b-3755-40b2-9bf2-3448cc67d6dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94211255-4d75-4bc2-87c1-ebb3707903e7 # Tabs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86c3425e-2859-4c26-96d2-b423a6b2690d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e76e75a-703a-4fa0-a4b7-6900bddca66f # Padding Classes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b65858f-6167-477b-b780-57e8a83de3c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a51ac343-0819-4000-af17-1116e3b9d533
        userCondition: null
fields:
  1e76e75a-703a-4fa0-a4b7-6900bddca66f: # Padding Classes
    columnSuffix: fdfumzdb
    contentColumnType: text
    fieldGroup: null
    handle: paddingClasses
    instructions: "Add padding classes to the block: [padding-type]-[padding-amount]\r\nptm (padding top mobile), ptb (padding bottom mobile), ptd (padding top desktop), pbd (padding bottom desktop)\r\ne.g. ptm-2 adds 2rem of padding top mobile"
    name: 'Padding Classes'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  94211255-4d75-4bc2-87c1-ebb3707903e7: # Tabs
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tabs
    instructions: null
    name: Tabs
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 378151983
      columns:
        __assoc__:
          -
            - 5ebbf446-f291-44cb-9ae9-77ccb6b2520f # Tab Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b177c7ba-2763-4f45-ab37-ddf88b5be6c1 # Tab Content
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_tabs}}'
      fieldLayout: row
      maxRows: 5
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: tabs
name: Tabs
sortOrder: 2
