field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  768c8f91-aad3-4d78-a27b-0bd0ffa4c37f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5fdd1eea-8c0a-4faa-9e5d-680a28656e75 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be4b80ef-02a5-4e94-965b-2b1729d7c91d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab58dbbc-8eae-4f97-8bd5-a07189671bdc # Sub heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61f03225-903c-4097-8f76-b09c97bc9b2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76585342-5767-4458-84dc-419642b772ec # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ca85455-2615-46db-b0fd-8ab3d63b3af4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7aacae89-3778-4eff-9cf5-bf1cdba5cca1
        userCondition: null
fields:
  5fdd1eea-8c0a-4faa-9e5d-680a28656e75: # Heading
    columnSuffix: scfrzeas
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  76585342-5767-4458-84dc-419642b772ec: # Testimonials
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: testimonials
    instructions: null
    name: Testimonials
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 379032592
      columns:
        __assoc__:
          -
            - 051cf5fd-907d-41fe-8172-064ba01abfca # Author
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6bfa45b8-0a4a-48e1-bedb-1fb0ec80cb2c # Testimonial
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_9_testimonials}}'
      fieldLayout: table
      maxRows: 5
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  ab58dbbc-8eae-4f97-8bd5-a07189671bdc: # Sub heading
    columnSuffix: xlmwilqy
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: null
    name: 'Sub heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testimonials
name: Testimonials
sortOrder: 7
