changedFieldIndicator: null
field: 2e322a3d-6592-4626-89bf-c3286fc7f809 # Legal Navigation
fieldLayouts:
  7d7bae30-f8cd-418b-878e-f5540427ed9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8466994d-4dfd-4f8f-89c4-b49c4d06c5e8 # Navlink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f159ff-01a9-4aec-a2d9-1a4afbd4d009
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33a52b50-92f9-4fa5-9849-ae754b26be74
        userCondition: null
fields:
  8466994d-4dfd-4f8f-89c4-b49c4d06c5e8: # Navlink
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: navlink
    instructions: null
    name: Navlink
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
