field: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
fieldLayouts:
  272b7a9e-e939-4a01-92ba-361818c1ce98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6f021952-9edc-4df6-ad77-d7a284524370 # Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ef579d8-ac01-4c0b-bb7e-21573cd59dff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a1fd4c3-4163-47c7-87a9-3bcfb92c04c1
        userCondition: null
fields:
  6f021952-9edc-4df6-ad77-d7a284524370: # Logos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logos
    instructions: null
    name: Logos
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1494974354
      columns:
        __assoc__:
          -
            - 35cacd4a-d8b1-47ba-a0be-38bc3c089aa6 # Logo
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_logos}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: logoMarquee
name: 'Logo Marquee'
sortOrder: 4
