fieldLayouts:
  08c581e5-2e06-4675-beba-897f77e15703:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e007cca-ba10-4364-8c14-9bcc9f37a396
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02e08cf1-f4fb-48eb-956f-953bf078d484 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 646b9866-7ab5-4db8-97d9-14f1ba7ab456
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5efeac22-bfea-4a54-9070-0bb0bb3431f1
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b63b37d8-78be-408f-9a6c-ab6463351d31 # Listing
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
