fieldLayouts:
  37404d42-409a-4230-9458-f6f80bfc527f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 313ca4a5-ebf0-4809-a742-705c3e15832b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3193946b-b765-4d14-a0ab-a4566728f07c # Content Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a72f41f6-dc88-4d07-9073-67fb35989599
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c4c5657-9793-4b15-9b77-5df478ac2907
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: cacf2ab9-82ca-4b60-9328-6dd17a39e489 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
