fieldLayouts:
  2313f566-ca5d-4daa-8788-a50330298dc2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d6904fc4-89ee-4207-9f1c-45db0690adb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1cf029e-2704-4b27-8938-0885c3b73003
        userCondition: null
fs: devSpace
handle: media
name: Media
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
