dateModified: 1677748255
email:
  fromEmail: marvin@butter.com.hk
  fromName: 'Butter Base'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  devSpace:
    hasUrls: true
    name: 'Dev Space'
    settings:
      bucket: $DEV_SPACES_BUCKET
      contentDisposition: ''
      endpoint: $DEV_SPACES_ENDPOINT
      expires: ''
      keyId: $DEV_SPACES_KEY
      region: $DEV_SPACES_REGION
      secret: $DEV_SPACES_SECRET
      subfolder: butterbase
    type: vaersaagod\dospaces\Fs
    url: $DEV_SPACES_BASE_URL
meta:
  __names__:
    00e79fbb-9025-48bc-86e0-6d1bba5d24ac: 'Tab Content' # Tab Content
    0e83711a-9cf5-475a-8870-95cf36695d4a: Heading # Heading
    0f5aadae-2721-41e8-933c-6e6c8efdaea6: 'Butter Base' # Butter Base
    1c0ef025-ba77-482c-b55c-d1e6f9666bad: Default # Default
    1c6f7825-37ef-467e-9bd9-880b6ebb7237: Description # Description
    1ccee473-50af-40c5-8250-aaa76096767d: Media # Media
    1e76e75a-703a-4fa0-a4b7-6900bddca66f: 'Padding Classes' # Padding Classes
    2b3c1a92-4bbb-4ccf-b6d5-255d67cad436: Tabs # Tabs
    02e08cf1-f4fb-48eb-956f-953bf078d484: Body # Body
    2e322a3d-6592-4626-89bf-c3286fc7f809: 'Legal Navigation' # Legal Navigation
    2e4337db-0083-4a95-8f08-bbadd4955177: Subtitle # Subtitle
    3ca4309c-3bd0-4452-820c-583090fee623: 'Slidie Title' # Slidie Title
    3e4a4791-081c-44e5-b696-27fe15365b85: 'Slide Content' # Slide Content
    5b0ff9ce-59f0-4c80-aa74-97bbcea5b5fc: navlink # navlink
    5ea4cbc3-8c8d-4915-aed3-b240ed09f0a0: Image # Image
    5ebbf446-f291-44cb-9ae9-77ccb6b2520f: 'Tab Heading' # Tab Heading
    5fdd1eea-8c0a-4faa-9e5d-680a28656e75: Heading # Heading
    6bfa45b8-0a4a-48e1-bedb-1fb0ec80cb2c: Testimonial # Testimonial
    6c7a48d4-7998-435f-8c90-3a90de3cbfea: Excerpt # Excerpt
    6f021952-9edc-4df6-ad77-d7a284524370: Logos # Logos
    7b9a2d77-1523-489b-8c4b-4bfcdfc7dbc3: Copyright # Copyright
    7ef48fe6-b2e7-4db6-8780-d05ca6e76712: Accordion # Accordion
    8c9b4348-184c-4e97-99a4-6d2a6157189c: Announcement # Announcement
    9c07bc61-0ec7-4e84-9f4b-ab5fb7cadbc3: 'Text Image' # Text Image
    11f753ea-a516-4464-b556-887ada297e53: 'Google Map Embed' # Google Map Embed
    17fb8838-f4d8-4a38-9156-1122b6ee8786: Body # Body
    34d757c2-6a46-4fac-abca-c39b46a73934: Heading # Heading
    35cacd4a-d8b1-47ba-a0be-38bc3c089aa6: Logo # Logo
    37c1a1db-b940-4cdd-ad3a-a123f35e1328: 'Public Schema' # Public Schema
    051cf5fd-907d-41fe-8172-064ba01abfca: Author # Author
    68f928fb-1a3a-4d60-bde4-8a8c7bbd28ae: Heading # Heading
    77efd199-d2df-4fbf-8a4b-a55cb0261ad7: 'Address Details' # Address Details
    78edba3e-0c3b-4229-a26a-38a8b83a1c35: Heading # Heading
    79aa842e-51cb-4aa2-887c-d237fc2a404f: Heading # Heading
    082c5614-1d5d-4619-bde0-482749dbd536: Accordion # Accordion
    85b0197e-141e-4615-8481-30a214206f1a: 'Contact Form' # Contact Form
    230f5dc9-0101-42f6-8cc5-aa93235c2396: 'Menu Title' # Menu Title
    240f0a17-fabc-400a-972b-f66a52e68c4f: Default # Default
    492a65c6-b7ba-4461-a03f-d56f9235cfbd: CTA # CTA
    559d5611-2026-4246-947d-c9a3483290ca: Image # Image
    614e8403-7e46-4e90-bfee-32b96e22392d: Heading # Heading
    801ae06f-6c06-400d-ad36-fc1d4017f972: Heading # Heading
    883ce90a-ab3e-4732-a747-7441c90a4b61: Body # Body
    919d3e3b-e519-41d6-bc52-9d7f689a94f3: Navlink # Navlink
    932ab354-ed04-4fc5-b29b-8c0940c05e3e: SlideLink # SlideLink
    3127e518-f710-485b-9cd9-68f3382f27b4: Body # Body
    3341b3a5-98b1-4993-ac5a-e98225baef6a: Body # Body
    7494fe72-686b-42b0-be10-ec1a377f204d: 'Image Position' # Image Position
    72756b12-b88c-44c1-9d00-947d14e9b5b9: Homepage # Homepage
    171101f6-dccd-4801-bec2-8f4dec8fe074: 'Address Details' # Address Details
    978805eb-fd33-418c-bc35-8c5f9919b7ff: Description # Description
    3193946b-b765-4d14-a0ab-a4566728f07c: 'Content Blocks' # Content Blocks
    4449155e-ddc4-41c4-bbcf-1328a4630e92: 'Feature Cards' # Feature Cards
    8466994d-4dfd-4f8f-89c4-b49c4d06c5e8: Navlink # Navlink
    56547699-1cf7-4bff-93c7-3c3a1b82d699: Footer # Footer
    61375875-bb85-4738-9c54-a5b16ee351c8: 'Public Schema' # Public Schema
    76585342-5767-4458-84dc-419642b772ec: Testimonials # Testimonials
    94211255-4d75-4bc2-87c1-ebb3707903e7: Tabs # Tabs
    a49e5098-eb39-419f-986b-3fd1111faac5: Slider # Slider
    a95ded72-28f3-40b1-84c8-7a4de0d59fdc: Accordion # Accordion
    a235ed0c-eb02-40e7-9562-90a73bbc794e: Accordion # Accordion
    a538233b-1b18-46b0-9149-9cc35131fb1e: Testimonials # Testimonials
    a933287e-e898-4dfe-b29f-7cda0599afd2: Heading # Heading
    ab58dbbc-8eae-4f97-8bd5-a07189671bdc: 'Sub heading' # Sub heading
    b5b45511-d660-4b43-99af-ecf49c21e74a: 'Butter Base' # Butter Base
    b6f093f0-e38b-466f-8c0f-1e8db96d4cd3: 'Menu Title' # Menu Title
    b55d7ffd-972e-47ea-963a-483533b482dc: Header # Header
    b63b37d8-78be-408f-9a6c-ab6463351d31: Listing # Listing
    b90fe952-cbf8-4780-9b6a-7ab674d54548: Body # Body
    b177c7ba-2763-4f45-ab37-ddf88b5be6c1: 'Tab Content' # Tab Content
    b520ddfe-6584-49bf-92d2-37b676bd9a5e: 'Test Field' # Test Field
    b427388b-54d0-4be8-bea8-55771d9bfa34: 'Call to action' # Call to action
    c074f4fe-289c-415e-9e81-8ce32db9b862: Image # Image
    c0852df2-0482-43b0-ae48-eeb443a415e7: 'Main Navigation' # Main Navigation
    c4a33146-25e2-4b36-97cb-b6bc2032389c: Pages # Pages
    c8d24909-9834-4afa-9c6d-dfc0f16ef9d2: Slide # Slide
    c2316d1e-96a1-48ef-9a2c-1fae3f850929: Submenu # Submenu
    c34894b7-2b1c-4ad1-bc12-7ac8f49ed8bc: 'Logo Marquee' # Logo Marquee
    c4119900-004c-4731-9081-de3a696eacde: Heading # Heading
    cacf2ab9-82ca-4b60-9328-6dd17a39e489: News # News
    ce124ebe-b018-4d4c-b53a-f76757514026: 'Tab Heading' # Tab Heading
    d2f74f8d-c18f-47d3-bf84-06ff803b0d92: Homepage # Homepage
    d5964d39-cf97-4afa-bd58-0decc4272b87: body # body
    db3fcb60-f719-40d3-bad4-77dd112dee6b: Heading # Heading
    e4d37003-92b6-46bf-a809-a834131fae21: 'Hero Banner' # Hero Banner
    e7643dbf-694d-4c36-a969-bb58c143f0c7: 'Enupal Test' # Enupal Test
    e19213fe-09b9-4f1b-be5f-0c6af684c979: 'Featured Items' # Featured Items
    ea94f442-5271-4806-9615-d5646aa78587: 'Content Blocks' # Content Blocks
    ea5053b7-2de8-4155-82a0-5a00464efa71: Default # Default
    ec4987e1-3168-49b9-a38c-688ef31547d8: 'Menu Group' # Menu Group
    f5d951bd-7589-4e90-a038-1d04fa2f7c1b: Common # Common
    f9de60c5-b728-4a0b-b1a4-07775d588038: Thumbnail # Thumbnail
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  enupal-translate:
    edition: standard
    enabled: true
    licenseKey: IIAXCVP74O8U1O91YW8N0EMI
    schemaVersion: 3.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields: ''
      from_email: devs@butter.com.hk
      from_name: ButterBase
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '2'
      success_message: 'Thank You! we will review your submission shortly.'
      volume_id: ''
system:
  edition: pro
  live: true
  name: 'Butter Base'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
