changedFieldIndicator: 2014819100
field: 94211255-4d75-4bc2-87c1-ebb3707903e7 # Tabs
fieldLayouts:
  29285989-44c3-4ef4-9d94-12f10365e971:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ce124ebe-b018-4d4c-b53a-f76757514026 # Tab Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c94c3ba2-ef6c-4ccb-8df8-73b1c6ff558b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00e79fbb-9025-48bc-86e0-6d1bba5d24ac # Tab Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87fb0019-b8c0-4721-8048-6e3526bd0724
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e527b601-a0e8-42c8-ab77-4428c63a9922
        userCondition: null
fields:
  00e79fbb-9025-48bc-86e0-6d1bba5d24ac: # Tab Content
    columnSuffix: khsjafrl
    contentColumnType: text
    fieldGroup: null
    handle: tabContent
    instructions: null
    name: 'Tab Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ce124ebe-b018-4d4c-b53a-f76757514026: # Tab Heading
    columnSuffix: wvctuqee
    contentColumnType: text
    fieldGroup: null
    handle: tabHeading
    instructions: null
    name: 'Tab Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
