<<<<<<< HEAD
changedFieldIndicator: 738699680
field: c8d24909-9834-4afa-9c6d-dfc0f16ef9d2 # Slide
fieldLayouts:
  c05894c2-202b-434b-a160-f3fe89873bae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ea4cbc3-8c8d-4915-aed3-b240ed09f0a0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 678084d1-143b-41bd-b26a-2c9a87e44a0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ca4309c-3bd0-4452-820c-583090fee623 # Slidie Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e39b0d72-bf5d-49b0-af81-f536c71dfdbf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e4a4791-081c-44e5-b696-27fe15365b85 # Slide Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97405f87-99d6-4c72-b8ba-d350b8c05e28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 932ab354-ed04-4fc5-b29b-8c0940c05e3e # SlideLink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef08c6f4-e1dd-4d65-8a7c-5087e54f1e5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c8e098e6-988b-404e-9f70-7cc02a3bde30
        userCondition: null
fields:
  3ca4309c-3bd0-4452-820c-583090fee623: # Slidie Title
    columnSuffix: kdccsegf
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: 'Slidie Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3e4a4791-081c-44e5-b696-27fe15365b85: # Slide Content
    columnSuffix: dnsvphos
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: null
    name: 'Slide Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5ea4cbc3-8c8d-4915-aed3-b240ed09f0a0: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  932ab354-ed04-4fc5-b29b-8c0940c05e3e: # SlideLink
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideLink
    instructions: null
    name: SlideLink
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
=======
changedFieldIndicator: 475095117
field: c8d24909-9834-4afa-9c6d-dfc0f16ef9d2 # Slide
fieldLayouts:
  c05894c2-202b-434b-a160-f3fe89873bae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ea4cbc3-8c8d-4915-aed3-b240ed09f0a0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 678084d1-143b-41bd-b26a-2c9a87e44a0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ca4309c-3bd0-4452-820c-583090fee623 # Slidie Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e39b0d72-bf5d-49b0-af81-f536c71dfdbf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e4a4791-081c-44e5-b696-27fe15365b85 # Slide Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97405f87-99d6-4c72-b8ba-d350b8c05e28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 932ab354-ed04-4fc5-b29b-8c0940c05e3e # SlideLink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef08c6f4-e1dd-4d65-8a7c-5087e54f1e5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c8e098e6-988b-404e-9f70-7cc02a3bde30
        userCondition: null
fields:
  3ca4309c-3bd0-4452-820c-583090fee623: # Slidie Title
    columnSuffix: kdccsegf
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: 'Slidie Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3e4a4791-081c-44e5-b696-27fe15365b85: # Slide Content
    columnSuffix: dnsvphos
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: null
    name: 'Slide Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5ea4cbc3-8c8d-4915-aed3-b240ed09f0a0: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1ccee473-50af-40c5-8250-aaa76096767d' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  932ab354-ed04-4fc5-b29b-8c0940c05e3e: # SlideLink
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slideLink
    instructions: null
    name: SlideLink
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
>>>>>>> 4012d9a (server yaml auto commit)
